// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVcyL28JlCCZpJXTxwuj4d4YKcOmIVM8',
    appId: '1:1048775576971:web:231dd10c316d5164dc338e',
    messagingSenderId: '1048775576971',
    projectId: 'fir-demo-94a45',
    authDomain: 'fir-demo-94a45.firebaseapp.com',
    storageBucket: 'fir-demo-94a45.appspot.com',
    measurementId: 'G-PF9VFN59ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEgCMFL52kPMIlGYf3Cj6_ljVVL_pNjXA',
    appId: '1:1048775576971:android:6df6f4c12ec56d80dc338e',
    messagingSenderId: '1048775576971',
    projectId: 'fir-demo-94a45',
    storageBucket: 'fir-demo-94a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W91YHqOGGCgk85qurjGjHHVb4Xb7ugQ',
    appId: '1:1048775576971:ios:e3c795a5106db43adc338e',
    messagingSenderId: '1048775576971',
    projectId: 'fir-demo-94a45',
    storageBucket: 'fir-demo-94a45.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W91YHqOGGCgk85qurjGjHHVb4Xb7ugQ',
    appId: '1:1048775576971:ios:e3c795a5106db43adc338e',
    messagingSenderId: '1048775576971',
    projectId: 'fir-demo-94a45',
    storageBucket: 'fir-demo-94a45.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoVcyL28JlCCZpJXTxwuj4d4YKcOmIVM8',
    appId: '1:1048775576971:web:191fec5faf008e07dc338e',
    messagingSenderId: '1048775576971',
    projectId: 'fir-demo-94a45',
    authDomain: 'fir-demo-94a45.firebaseapp.com',
    storageBucket: 'fir-demo-94a45.appspot.com',
    measurementId: 'G-ZWEXPDY88N',
  );
}
